web: 
  upload-path: /var/uploads/

spring: 
  resources: 
    static-locations: 
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:${web.upload-path}